first commit
RnD-2020/sritej-reddy-C-Learner pull request #1
Opened 2019-09-18 14:40 UTC by sritej-reddy

2019-09-20 05:09 UTC, krushiraj requested changes
Please commit with the requested changes.

2019-09-20 05:09 UTC, krushiraj commented on src/count.cpp
> +	}
Can you think of any solution without using iterations and make this an O(1) solution?

2019-09-20 05:09 UTC, krushiraj commented on src/countFactorials.cpp
> +
Can you discuss the drawbacks of this algo and what can be done to fix it?

2019-09-20 05:09 UTC, krushiraj commented on src/countOnes.cpp
> +	unsigned long i=111;
did you check for the overflow conditions here?

2019-09-20 05:09 UTC, krushiraj commented on src/decimalToOctal.cpp
> +
So here pow is being called `the no of digits in num times`. Can you make of use of pow only once and get the solution done by having a lesser cost operations like math operations?

2019-09-20 05:09 UTC, krushiraj commented on src/isOlder.cpp
> +
Re-write the whole thing by breaking it into functions and make it more modular and easy to look and understand.

2019-09-20 05:09 UTC, krushiraj commented on src/isPerfect.cpp
> +	{
Good optimization strategy by checking upto `num/2`

2019-09-20 05:09 UTC, krushiraj commented on src/nthNumber.cpp
> +	{
All primes are odds, can you make use of this fact and optimize the function to some more extent?

2019-09-20 05:09 UTC, krushiraj commented on src/octalToHexadecimal.cpp
> +		dec /= 16;
Same here, try to make use of pow less no of times.

2019-09-20 05:09 UTC, krushiraj commented on src/octalToHexadecimal.cpp
> +	return hex;
Good to see that you tried this for >10.

2019-09-20 05:09 UTC, krushiraj commented on src/swapBits.cpp
> +
I guess you can do it in simpler algo. 

HINT: try to make use of operators in C that work on bits of numbers.

2019-09-20 14:00 UTC, sritej-reddy commented on src/countOnes.cpp
> +	unsigned long i=111;
yes it is overflowing..manoj said he asked you about it and you said to him that you will check the question ones so i ignored that exception

2019-09-20 15:13 UTC, sritej-reddy commented on src/nthNumber.cpp
> +	{
ohk done

2019-09-20 17:34 UTC, sritej-reddy commented on src/countOnes.cpp
> +	unsigned long i=111;
anna i got a solution for it now..it may work

2019-09-20 17:54 UTC, sritej-reddy commented on src/countOnes.cpp
> +	unsigned long i=111;
vacchindi anna

2019-09-23 17:22 UTC, sritej-reddy commented on src/countFactorials.cpp
> +
in every iteration factorial is found, it is a time taking process, so to solve this we can compute factorial in other way (storing a number and multiplying it with next number in the next iteration, as finding the factorials in this problem is of consequence numbers)

2019-09-23 17:23 UTC, sritej-reddy commented on src/countFactorials.cpp
> +
i will make required changes and commit it to master branch

2019-09-23 18:00 UTC, closed without merging