Chap1 assg
RnD-2020/sritej-reddy-C-Learner pull request #18
Opened 2019-10-23 14:35 UTC by sritej-reddy

2019-10-24 06:54 UTC, krushiraj requested changes
Just change that one code. Everything else is okay!

2019-10-24 06:54 UTC, krushiraj commented on c-unit1-assignments/src/Assignment_02.cpp
> +		while (i >= 0)
Oka while ni oka separate function ga rasko better.

2019-10-24 18:19 UTC, sritej-reddy commented on c-unit1-assignments/src/Assignment_02.cpp
> +		while (i >= 0)
Done. closes #18

2019-10-26 15:58 UTC, sritej-reddy commented on c-unit1-assignments/src/Assignment_02.cpp
> +		while (i >= 0)
anna ayindi commit chesina

2019-10-26 16:12 UTC, krushiraj approved these changes
Merging this.

2019-10-26 16:12 UTC, krushiraj commented on c-unit1-assignments/src/Assignment_02.cpp
> +}
This looks great now.

2019-10-26 16:13 UTC, merged