Code complexity
RnD-2020/sritej-reddy-C-Learner pull request #19
Opened 2019-10-31 16:35 UTC by sritej-reddy

2019-10-31 16:36 UTC, sritej-reddy commented
closes #19

2019-10-31 17:04 UTC, krushiraj requested changes
Please come up with the changes that I have requested in the comments

2019-10-31 17:04 UTC, krushiraj commented on CodeComplexity/src/TimeComplexity.cpp
> +	return "O(n)";
Please write comments before each return statement about why did you feel that the function has a certain time complexity, that whichever value you are returning. Give reasoning.

2019-10-31 17:04 UTC, krushiraj commented on CodeComplexity/src/TwoSum.cpp
> +What is the complexity of this method ? __________
Can you please fill these out?

2019-11-02 18:32 UTC, sritej-reddy commented
anna i have a question in function11 worst case should be n*n*n right? because worst case can be an array with all same elements.

2019-11-03 05:08 UTC, sritej-reddy commented
I got answer👍👍

2019-11-06 10:24 UTC, krushiraj approved these changes
Everything is okay. Merging this.

2019-11-06 10:25 UTC, merged