Week1
RnD-2020/sritej-reddy-C-Learner pull request #20
Opened 2019-11-12 12:13 UTC by sritej-reddy

2019-11-18 17:25 UTC, krushiraj commented on C-Arrays/src/maxPosNegSum.cpp
> +	if (positive_count && negative_count)
Good check for edge cases.

2019-11-18 17:27 UTC, krushiraj commented on C-Arrays/src/nPrime.cpp
> +			arr=storeInArray(arr, i,k);
Good that this is modular. :D

2019-11-18 17:40 UTC, krushiraj requested changes
Please come up with the requested changes.

2019-11-18 17:40 UTC, krushiraj commented on C-Arrays/src/scoresDescendingSort.cpp
> +	while (i < n1 && j < n2)
Can extract each of the while loop to a new function. Not mandatory but it would be good.

2019-11-18 17:40 UTC, krushiraj commented on C-Strings/src/KthIndexFromEnd.cpp
> +	return str[strlen(str) - 1 - K];
what if K < 0 or K > len?

2019-11-22 14:35 UTC, sritej-reddy commented
made modular and added condition check for K. closes #20

2019-11-29 05:39 UTC, krushiraj approved these changes
Merging this. I hope there are no other pending actions on this PR. If there are any please re-open the PR.

2019-11-29 05:39 UTC, krushiraj commented on C-Strings/src/KthIndexFromEnd.cpp
> +	return str[strlen(str) - 1 - K];
Yeah. Now this looks prefect.

2019-11-29 05:39 UTC, merged