Chap2 testing
RnD-2020/sritej-reddy-C-Learner pull request #7
Opened 2019-10-13 07:25 UTC by sritej-reddy

2019-10-15 04:49 UTC, krushiraj commented on C-NumberSystem/src/ButterflyNumber.cpp
> +	if (N < 0)
Good to see the comments

2019-10-15 04:51 UTC, krushiraj requested changes
All good and ready to be merged except for that semi-colon removal. Just remove that extra semi-colon and commit. We can merge this.

2019-10-15 04:51 UTC, krushiraj commented on C-NumberSystem/src/Swap.cpp
> +	int t;;
remove extra semi-colon here.

2019-10-15 07:20 UTC, sritej-reddy commented on C-NumberSystem/src/Swap.cpp
> +	int t;;
i removed it and commited.

2019-10-15 15:16 UTC, sritej-reddy commented on C-NumberSystem/src/Swap.cpp
> +	int t;;
closes #7

2019-10-16 04:58 UTC, krushiraj approved these changes
All good. I'm merging this now.

2019-10-16 04:59 UTC, merged